In [1]:
import pandas as pd
l=[18,20,10,12,15]
b=[20,20,10,15,17]
df=pd.DataFrame({"length":l,"breadth":b})
print(df)

   length  breadth
0      18       20
1      20       20
2      10       10
3      12       15
4      15       17

In [5]:
df["area"]=df["length"]*df["breadth"]
df["area1"]=df["area"]+20
df

   length  breadth  area  area1
0      18       20   360    380
1      20       20   400    420
2      10       10   100    120
3      12       15   180    200
4      15       17   255    275

In [11]:
df=pd.DataFrame({"rollno":[1,2,3,4,5],"city":["a","b","c","b","a"]})
print(df)
df1=pd.get_dummies(data=df,drop_first=True)
df1

   rollno city
0       1    a
1       2    b
2       3    c
3       4    b
4       5    a

   rollno  city_b  city_c
0       1   False   False
1       2    True   False
2       3   False    True
3       4    True   False
4       5   False   False

In [12]:
import pandas as pd
l=[18,20,10,12,15]
b=[20,20,10,15,17]
df=pd.DataFrame({"length":l,"breadth":b})
df["area"]=df["length"]*df["breadth"]
df["price"]=[3000000,4000000,2000000,2500000,1500000]
print(df)

import numpy as np
df["price"]=np.where(df["price"]>=3000000,"high",
                    np.where(df["price"]>=2000000,"med","low"))
df

   length  breadth  area    price
0      18       20   360  3000000
1      20       20   400  4000000
2      10       10   100  2000000
3      12       15   180  2500000
4      15       17   255  1500000

   length  breadth  area price
0      18       20   360  high
1      20       20   400  high
2      10       10   100   med
3      12       15   180   med
4      15       17   255   low

In [24]:
df=pd.read_csv("car data.csv")

df["car_age"]=2026-df["Year"]
print(df.info())

x=df[["car_age","Present_Price","Kms_Driven","Fuel_Type","Seller_Type","Transmission"]]
y=df["Selling_Price"]
x=pd.get_dummies(data=x,drop_first=True)
print(x)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=41)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
 9   car_age        301 non-null    int64
dtypes: float64(2), int64(4), object(4)
memory usage: 23.6+ KB
None
     car_age  Present_Price  Kms_Driven  Fuel_Type_Diesel  Fuel_Type_Petrol  \
0         12           5.59       27000             False              True
1         13           9.54       43000              True             False
2          9           9.85        6900             False              True
3         15           4.15        5200             False              True
4         12           6.87       42450              True             False
..       ...            ...         ...               ...               ...
296       10          11.60       33988              True             False
297       11           5.90       60000             False              True
298       17          11.00       87934             False              True
299        9          12.50        9000              True             False
300       10           5.90        5464             False              True

     Seller_Type_Individual  Transmission_Manual
0                     False                 True
1                     False                 True
2                     False                 True
3                     False                 True
4                     False                 True
..                      ...                  ...
296                   False                 True
297                   False                 True
298                   False                 True
299                   False                 True
300                   False                 True

[301 rows x 7 columns]
(240, 7)
(240,)
(61, 7)
(61,)