In [21]:
import pandas as pd
data = [20,30,40,50]
ds = pd.Series(data)
print(ds)

0    20
1    30
2    40
3    50
dtype: int64

In [22]:
import numpy as np
ds1 = pd.Series(np.array([10,20,30]))
print(ds1)

0    10
1    20
2    30
dtype: int32

In [23]:
ds2 = pd.Series(range(1,6))
print(ds2)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [24]:
ds3 = pd.Series({'a':20,'b':30,'c':25})
print(ds3)

a    20
b    30
c    25
dtype: int64

In [25]:
ds4 = pd.Series([20,30,40,50],index=['A','B','C','D'])
print(ds4)
type(ds4)

A    20
B    30
C    40
D    50
dtype: int64

pandas.core.series.Series

In [40]:
import pandas as pd
data = {'name':['A','B','C','D'],'city':['Abd','Surat','Baroda','Rajkot'],'Div':['D1','D2','D3','D4'],'Marks':[400,300,350,250]}
df = pd.DataFrame(data)
print(df)

  name    city Div  Marks
0    A     Abd  D1    400
1    B   Surat  D2    300
2    C  Baroda  D3    350
3    D  Rajkot  D4    250

In [41]:
d = [['D1',20],
    ['D2',30],
    ['D3',40]]

df1 = pd.DataFrame(d,columns=['div','Marks'],index=['A','B','C'])
print(df1)

  div  Marks
A  D1     20
B  D2     30
C  D3     40

In [42]:
s1 = pd.Series([10,20,30])
s2 = pd.Series([100,200,300])
df2 = pd.DataFrame({'col1':s1,
                   'col2':s2})
print(ds2)

  div name
0  d1  Raj
1  d2   om

In [43]:
d = [{'div':'d1','name':'Raj'},
    {'div':'d2','name':'om'}]

df2 = pd.DataFrame(d)
print(ds2)

  div name
0  d1  Raj
1  d2   om

In [44]:
df1 = pd.DataFrame()
print(df1)

Empty DataFrame
Columns: []
Index: []

In [45]:
df=pd.read_csv('car.csv')
print(df)

           Car       Model  Volume  Weight  CO2  Unnamed: 5
0       Toyota        Aygo    1000     790   99         NaN
1   Mitsubishi  Space Star    1200    1160   95         NaN
2        Skoda      Citigo    1000     929   95         NaN
3         Fiat         500     900     865   90         NaN
4         Mini      Cooper    1500    1140  105         NaN
5           VW         Up!    1000     929  105         NaN
6        Skoda       Fabia    1400    1109   90         NaN
7     Mercedes     A-Class    1500    1365   92         NaN
8         Ford      Fiesta    1500    1112   98         NaN
9         Audi          A1    1600    1150   99         NaN
10     Hyundai         I20    1100     980   99         NaN
11      Suzuki       Swift    1300     990  101         NaN
12        Ford      Fiesta    1000    1112   99         NaN
13       Honda       Civic    1600    1252   94         NaN
14      Hundai         I30    1600    1326   97         NaN
15        Opel       Astra    1600    1330   97         NaN
16         BMW           1    1600    1365   99         NaN
17       Mazda           3    2200    1280  104         NaN
18       Skoda       Rapid    1600    1119  104         NaN
19        Ford       Focus    2000    1328  105         NaN
20        Ford      Mondeo    1600    1584   94         NaN
21        Opel    Insignia    2000    1428   99         NaN
22    Mercedes     C-Class    2100    1365   99         NaN
23       Skoda     Octavia    1600    1415   99         NaN
24       Volvo         S60    2000    1415   99         NaN
25    Mercedes         CLA    1500    1465  102         NaN
26        Audi          A4    2000    1490  104         NaN
27        Audi          A6    2000    1725  114         NaN
28       Volvo         V70    1600    1523  109         NaN
29         BMW           5    2000    1705  114         NaN
30    Mercedes     E-Class    2100    1605  115         NaN
31       Volvo        XC70    2000    1746  117         NaN
32        Ford       B-Max    1600    1235  104         NaN
33         BMW           2    1600    1390  108         NaN
34        Opel      Zafira    1600    1405  109         NaN
35    Mercedes         SLK    2500    1395  120         NaN

In [46]:
df2.to_csv('csv1.csv')

In [50]:
%%writefile 'd1.csv'
name,div,marks
A,D1,20
B,D2,30
C,D3,40

Overwriting d1.csv

In [62]:
df = pd.DataFrame(data)
print(df)
df.set_index('Div',drop=True,inplace=False)

  name    city Div  Marks
0    A     Abd  D1    400
1    B   Surat  D2    300
2    C  Baroda  D3    350
3    D  Rajkot  D4    250

    name    city  Marks
Div
D1     A     Abd    400
D2     B   Surat    300
D3     C  Baroda    350
D4     D  Rajkot    250

In [64]:
df.reset_index(inplace=True)
df

   level_0  index name    city Div  Marks
0        0      0    A     Abd  D1    400
1        1      1    B   Surat  D2    300
2        2      2    C  Baroda  D3    350
3        3      3    D  Rajkot  D4    250

In [66]:
df = pd.read_csv('auto-mpg.csv')
type(df)

pandas.core.frame.DataFrame

In [68]:
df.head()               # first 5 rows

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [69]:
df.head(7)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala

In [70]:
df.tail()               #last 5 rows

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [71]:
df.tail(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
388,26.0,4,156.0,92,2585,14.5,82,1,chrysler lebaron medallion
389,22.0,6,232.0,112,2835,14.7,82,1,ford granada l
390,32.0,4,144.0,96,2665,13.9,82,3,toyota celica gt
391,36.0,4,135.0,84,2370,13.0,82,1,dodge charger 2.2
392,27.0,4,151.0,90,2950,17.3,82,1,chevrolet camaro
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [73]:
df.size

3582

In [74]:
df.values

array([[18.0, 8, 307.0, ..., 70, 1, 'chevrolet chevelle malibu'],
       [15.0, 8, 350.0, ..., 70, 1, 'buick skylark 320'],
       [18.0, 8, 318.0, ..., 70, 1, 'plymouth satellite'],
       ...,
       [32.0, 4, 135.0, ..., 82, 1, 'dodge rampage'],
       [28.0, 4, 120.0, ..., 82, 1, 'ford ranger'],
       [31.0, 4, 119.0, ..., 82, 1, 'chevy s-10']], dtype=object)

In [75]:
df.ndim                 # dimension

2

In [76]:
df.shape               #(rows,cols)

(398, 9)

In [77]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [78]:
df.sample(2)                    # random 2 samples

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
12,15.0,8,400.0,150,3761,9.5,70,1,chevrolet monte carlo
390,32.0,4,144.0,96,2665,13.9,82,3,toyota celica gt

In [79]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [3]:
import pandas as pd
df = pd.read_csv("auto-mpg.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [4]:
print(df)

      mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0
1    15.0          8         350.0        165    3693          11.5
2    18.0          8         318.0        150    3436          11.0
3    16.0          8         304.0        150    3433          12.0
4    17.0          8         302.0        140    3449          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4         140.0         86    2790          15.6
394  44.0          4          97.0         52    2130          24.6
395  32.0          4         135.0         84    2295          11.6
396  28.0          4         120.0         79    2625          18.6
397  31.0          4         119.0         82    2720          19.4

     model year  origin                   car name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]

In [6]:
df.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [7]:
df.describe(include='all')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
count,398.000000,398.000000,398.000000,398,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,150,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,NaN,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,NaN,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,NaN,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,NaN,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,NaN,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,NaN,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,NaN,5140.000000,24.800000,82.000000,3.000000,NaN

In [8]:
df.describe(exclude=['float64'])

         cylinders horsepower       weight  model year      origin    car name
count   398.000000        398   398.000000  398.000000  398.000000         398
unique         NaN         94          NaN         NaN         NaN         305
top            NaN        150          NaN         NaN         NaN  ford pinto
freq           NaN         22          NaN         NaN         NaN           6
mean      5.454774        NaN  2970.424623   76.010050    1.572864         NaN
std       1.701004        NaN   846.841774    3.697627    0.802055         NaN
min       3.000000        NaN  1613.000000   70.000000    1.000000         NaN
25%       4.000000        NaN  2223.750000   73.000000    1.000000         NaN
50%       4.000000        NaN  2803.500000   76.000000    1.000000         NaN
75%       8.000000        NaN  3608.000000   79.000000    2.000000         NaN
max       8.000000        NaN  5140.000000   82.000000    3.000000         NaN

In [9]:
df.describe(percentiles = [0.37,0.85])

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
37%,19.378000,4.000000,120.890000,2505.340000,14.500000,74.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
85%,32.245000,8.000000,318.000000,4067.650000,18.500000,80.450000,3.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [88]:
d = {'name':['Sachin','Lara','Root','Cook'],
    'runs':[15900,11900,13900,12400],
    'average':[53.8,52.8,51.1,45.3]}

df=pd.DataFrame(d)
print(df)

     name   runs  average
0  Sachin  15900     53.8
1    Lara  11900     52.8
2    Root  13900     51.1
3    Cook  12400     45.3

In [89]:
print(df.index)

RangeIndex(start=0, stop=4, step=1)

In [90]:
print(df['runs'])

0    15900
1    11900
2    13900
3    12400
Name: runs, dtype: int64

In [91]:
print(df[['name','runs']])

     name   runs
0  Sachin  15900
1    Lara  11900
2    Root  13900
3    Cook  12400

In [92]:
df.loc[1]

name        Lara
runs       11900
average     52.8
Name: 1, dtype: object

In [93]:
df.iloc[1]

name        Lara
runs       11900
average     52.8
Name: 1, dtype: object

In [94]:
df.loc[0:3]

     name   runs  average
0  Sachin  15900     53.8
1    Lara  11900     52.8
2    Root  13900     51.1
3    Cook  12400     45.3

In [95]:
df.iloc[0:3]

     name   runs  average
0  Sachin  15900     53.8
1    Lara  11900     52.8
2    Root  13900     51.1

In [96]:
df.loc[1,'name'] ='xyz'
print(df)

     name   runs  average
0  Sachin  15900     53.8
1     xyz  11900     52.8
2    Root  13900     51.1
3    Cook  12400     45.3

In [97]:
df.loc[:,'runs']

0    15900
1    11900
2    13900
3    12400
Name: runs, dtype: int64

In [98]:
df.loc[4] = ['Kallis',13200,55.3]
print(df)

     name   runs  average
0  Sachin  15900     53.8
1     xyz  11900     52.8
2    Root  13900     51.1
3    Cook  12400     45.3
4  Kallis  13200     55.3

In [99]:
df['matches']=[200,131,163,161,166]
print(df)

     name   runs  average  matches
0  Sachin  15900     53.8      200
1     xyz  11900     52.8      131
2    Root  13900     51.1      163
3    Cook  12400     45.3      161
4  Kallis  13200     55.3      166

In [100]:
df.loc[:,'Centuries']=[51,34,41,33,45]
print(df)

     name   runs  average  matches  Centuries
0  Sachin  15900     53.8      200         51
1     xyz  11900     52.8      131         34
2    Root  13900     51.1      163         41
3    Cook  12400     45.3      161         33
4  Kallis  13200     55.3      166         45

In [101]:
df['Performance']='good'
print(df)

     name   runs  average  matches  Centuries Performance
0  Sachin  15900     53.8      200         51        good
1     xyz  11900     52.8      131         34        good
2    Root  13900     51.1      163         41        good
3    Cook  12400     45.3      161         33        good
4  Kallis  13200     55.3      166         45        good

In [102]:
df.loc[df['average']<50,'Performance']='Avg'
print(df)

     name   runs  average  matches  Centuries Performance
0  Sachin  15900     53.8      200         51        good
1     xyz  11900     52.8      131         34        good
2    Root  13900     51.1      163         41        good
3    Cook  12400     45.3      161         33         Avg
4  Kallis  13200     55.3      166         45        good

In [103]:
import pandas as pd
df=pd.read_csv('sales_data.csv')
print(df)

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
7       NaN    NaN      NaN       NaN
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [106]:
print(df.isna())

     name  region  sales  expenses
0   False    True  False     False
1   False   False  False     False
2   False   False   True      True
3   False    True   True      True
4   False   False  False     False
5   False   False  False     False
6   False   False  False     False
7    True    True   True      True
8   False   False  False     False
9   False   False  False     False
10  False   False  False     False

In [107]:
print(df.isna().sum())

name        1
region      3
sales       3
expenses    3
dtype: int64

In [112]:
df.dropna()          # axis=0

      name region    sales  expenses
1     Emma  North  52000.0   43000.0
4   Edward   West  42000.0   38000.0
5   Thomas   West  72000.0   39000.0
6    Ethan  South  49000.0   42000.0
8     Arun   West  67000.0   39000.0
9    Anika   East  65000.0   50000.0
10   Paulo  South  67000.0   45000.0

In [113]:
df.dropna(axis=1)        # inplace=true

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [114]:
df.dropna(thresh=2)

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [115]:
df.dropna(how='all')

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [116]:
df.dropna(how='any')

      name region    sales  expenses
1     Emma  North  52000.0   43000.0
4   Edward   West  42000.0   38000.0
5   Thomas   West  72000.0   39000.0
6    Ethan  South  49000.0   42000.0
8     Arun   West  67000.0   39000.0
9    Anika   East  65000.0   50000.0
10   Paulo  South  67000.0   45000.0

In [121]:
df.dropna(subset=['sales','expenses'])

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [123]:
df['sales'].fillna(7)

0     50000.0
1     52000.0
2         7.0
3         7.0
4     42000.0
5     72000.0
6     49000.0
7         7.0
8     67000.0
9     65000.0
10    67000.0
Name: sales, dtype: float64

In [124]:
df['sales'].fillna(df['sales'].mean())

0     50000.0
1     52000.0
2     58000.0
3     58000.0
4     42000.0
5     72000.0
6     49000.0
7     58000.0
8     67000.0
9     65000.0
10    67000.0
Name: sales, dtype: float64

In [125]:
df.fillna(1)

       name region    sales  expenses
0   William      1  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      1.0       1.0
3    Markus      1      1.0       1.0
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
7         1      1      1.0       1.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0